site_name: The SC Proposition
site_url: https://sixslime.github.io/sc-proposition
theme:
  name: material
  font:
    text: "Atkinson Hyperlegible"
    code: "JetBrains Mono"
  palette:
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: blue grey
      accent: teal

    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
      primary: cyan
      accent: deep purple
  features:
    - navigation.path
    - navigation.indexes
    - navigation.footer
nav:
  - Main: index.md
  - Public & Private Content: public_private.md
  - Owned Objects: owned.md
  - Public Functions: functions.md
  - SlimeCore:
    - slimecore/index.md
    - Installation: slimecore/installation.md
