site_name: The SC Proposition
site_url: https://sixslime.github.io/sc-proposition
theme:
  name: material
  font:
    text: "Atkinson Hyperlegible"
    code: "JetBrains Mono"
  palette:
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: blue grey
      accent: teal

    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
      primary: blue grey
      accent: indigo
  features:
    - navigation.path
    - navigation.indexes
    - navigation.footer
    - navigation.sections
nav:
  - Introduction: index.md
  - Terminology: terminology.md
  - Rules:
    - rules/index.md
    - Primary Namespace: rules/primary_namespace.md
    - Private Content: rules/private.md
    - Owned Objects: rules/owned.md
    - Scoreboards: rules/scoreboards.md
    - NBT Storage Locations: rules/nbt_storage.md
    - Custom Data Namespacing: rules/nbt_namespacing.md
    - Public Functions: rules/functions.md
    - Function Tags: rules/function_tags.md
    - Pack Config: rules/config.md
    - Naming Specifications: rules/naming.md
    - Mcdoc: rules/mcdoc.md
  - SlimeCore:
    - slimecore/index.md
    - Pack Manifests: slimecore/manifest.md
    - Top-Level Function Tags: slimecore/special_tags.md
    - Loading & Rebuilding: slimecore/rebuilding.md
    - SlimeCore Data: slimecore/data.md
    - Datapack Naming: slimecore/datapack_names.md
  - Known Issues: issues.md