site_name: The SC Proposition
site_url: https://sixslime.github.io/sc-proposition
theme:
  name: material
  font:
    text: "Atkinson Hyperlegible"
    code: "JetBrains Mono"
  palette:
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: blue grey
      accent: teal

    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
      primary: cyan
      accent: deep purple
  features:
    - navigation.path
    - navigation.indexes
    - navigation.footer
    - navigation.sections
nav:
  - Main: index.md
  - Private Content: private.md
  - Owned Objects: owned.md
  - Public Functions: functions.md
  - SlimeCore:
    - slimecore/index.md
    - Pack Manifests: slimecore/manifest.md
    - Required Function Tags: slimecore/special_tags.md
    - Loading & Rebuilding: slimecore/rebuilding.md
    - SlimeCore Data: slimecore/data.md
    - Concepts: slimecore/concepts.md